server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order_db
    username: root
    password: Zhanglu1997!
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  application:
    name: order-service

  config:
    import: "configserver:http://localhost:8051"

